spring:
  config:
    import: optional:dotenv:.env
  datasource:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha # Organiza os endpoints em ordem alfabética
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

# Configuração JWT
# IMPORTANTE: Em produção, substitua o secret por uma variável de ambiente segura
jwt:
  secret: cGl6emFwdWItc2VjcmV0LWtleS0yMDI2LXN1cGVyLXNlY3VyZS1qd3Q=
  expiration: 86400000 # 24 horas em milissegundos